### PR TITLE
ADH Branding

### PR DESCRIPTION
**Pull request by anton-dahlin**

### CODE REVIEW

**Review by derekendres — APPROVED** [review]

**Comment by kelseyduffy** [comment]
looks like the pom version was missed in the library PR. it still says 0.1.9, so maven cant find the 0.2.0 version when building this

**Comment by anton-dahlin** [comment]
> looks like the pom version was missed in the library PR. it still says 0.1.9, so maven cant find the 0.2.0 version when building this

Thank you @kelseyduffy!

**Review by kelseyduffy — APPROVED** [review]

**Pull request merged**
